// This file is auto-generated by `mneme init`.
// It registers 12 mneme tools (task management, fact access, status)
// and a compaction hook for the OpenCode agent system.
//
// See the full source at: https://github.com/CVPaul/mneme
//
// Tools provided:
//   mneme_ready, mneme_list, mneme_show, mneme_create,
//   mneme_update, mneme_close, mneme_blocked, mneme_dep,
//   mneme_facts, mneme_propose_fact, mneme_status, mneme_doctor
